server:
  port: 2001
spring:
  cloud:
    gateway:
      routes:
        - id: github-blog
          uri: https://github.com/qijianguo
          predicates:
            - Path=/home
        - id: github-blog2
          uri: https://github.com/qijianguo
          predicates:
            # 1.Path路由断言工厂
            #- Path=/**  # 多级目录
            #- Path=/qijianguo/{segment}/blob   # 接收一个参数
            # 2.Query路由断言工厂
            #- Query=foo, ba.  # 接收两个参数，foo必选，ba是可选的
            # 3.Method路由断言工厂
            #- Method=GET
            # 4.Header路由断言工厂
            #- Header=X-Request-Id, \d+
            # 5.自定义路由工厂
            - name: CheckAuth
              args:
                name: github
        - id: user-service
          uri: lb://user-service    # lb代表从注册中心获取
          predicates:
            - Path=/user-service/**
      discovery:
        locator:
          # http://网关地址/服务名称/**
          enabled: true
          #（注意： 不配置`lower-case-service-id: true`时，服务名称必须大写，不配置或配置为false时只能用小写访问，二者只能二选一）
          lower-case-service-id: true   # 不区分服务名称的大小写